version: "3"
services:
  web:
    restart: always
    image: elavaud/easynut:1
    expose:
      - "8000"
    depends_on:
      - mysql
      - redis
    env_file: .env
    volumes:
      - django_static:/data/web/easynut/static
      - ./backups/backups:/opt/shared
    container_name: easynut_django
    networks:
      front-end:
        ipv4_address: 172.20.0.2
      back-end:
        ipv4_address: 172.21.0.2
    working_dir: /data/web/easynut
    command: [sh, -c, "/usr/bin/gunicorn django_easynut.wsgi:application -w 2 -b :8000"]
  nginx:
    restart: always
    image: nginx:1.13-alpine
    build:
      context: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - web
    container_name: easynut_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - django_static:/data/web/easynut/static
      - ./logs/nginx:/var/log/nginx
    networks:
      front-end:
        ipv4_address: 172.20.0.3
  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
    networks:
      back-end:
        ipv4_address: 172.21.0.4
    container_name: easynut_mysql
  redis:
    restart: always
    image: redis:4.0.6-alpine
    expose:
      - "6379"
    container_name: easynut_redis
    networks:
      back-end:
        ipv4_address: 172.21.0.5
  backups:
    restart: always
    image: alpine:3.7
    build:
      context: ./backups/
      args:
        DATA_DB_NAME: ${DATA_DB_NAME}
        CRON_TIME: ${CRON_TIME}
    env_file: .env
    depends_on:
      - mysql 
      - web
    volumes:
      - ./backups/backups:/backup
    container_name: easynut_backups
    networks:
      back-end:
        ipv4_address: 172.21.0.6

volumes:
  django_static:
  mysql_data:

networks:
  front-end:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.20.0.0/16
  back-end:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
